[gcp_service_account]
type = "service_account"
project_id = "digital-splicer-462115-a7"
private_key_id = "b90a3c60e45be48919c9b679ea2159aa75cad5fa"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDXtuxaS00KgYiH
...
-----END PRIVATE KEY-----"""
client_email = "dr-diyar-clinic@digital-splicer-462115-a7.iam.gserviceaccount.com"
client_id = "104046307930348282365"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/dr-diyar-clinic%40digital-splicer-462115-a7.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
